backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: d564aaed015c7a5d0838

collections:
  - name: "data" # Used in routes, e.g., /admin/collections/blog
    label: "data" # Used in the UI
    files:
      - label: "cv"
        name: "cv"
        file: "data/cv.yml"
        widget: list
        fields: # The fields for eacmh document, usually in front matter
          - {label: Name, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Works
            name: work
            widget: list
            allow_add: true
            fields:
              - { label: "Company", name: "company", widget: "string" }
              - { label: "Timespan", name: "timespan", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }