backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: d564aaed015c7a5d0838

collections:
  - name: "work" # Used in routes, e.g., /admin/collections/blog
    label: "Work" # Used in the UI
    folder: "_posts/work" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Timespan", name: "timespan", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }